ZVM_VI_INSERT_ESCAPE_BINDKEY=jj
export PATH="/home/zach/.cargo/bin:/snap/bin:$HOME/.local/bin:$PATH"
eval "$(starship init zsh)" 
eval "$(zoxide init zsh)"
alias exa='exa --group-directories-first'
alias vi='nvim'
alias l='exa'
alias la='exa -la'
alias a='exa -a'
alias j='z'
dot (){/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME "$@";}
dot-ls (){/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME ls-tree --full-tree -r HEAD;}
# find files changed in the .config directory in the last day 
alias nf='fdfind . /home/zach/.config -H --changed-within 1d -E Code -E google-chrome -x /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME ls-files --others {} | sort | uniq'
# git add files that changed in last day in .config
alias nfa='fdfind . /home/zach/.config -H --changed-within 1d -E chromium -x /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME ls-files --others {} | uniq | rargs /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME add {0}'
# Virtual environment.
# Show current virtual environment (Python).
#
#
export VIRTUAL_ENV_DISABLE_PROMPT=true

spaceship_venv_status() {
  [[ $SPACESHIP_VENV_SHOW == false ]] && return

  # Check if the current directory running via Virtualenv
  [ -n "$VIRTUAL_ENV" ] || return
  echo -n " %Bvia%b "
  echo -n "%{$fg_bold[blue]%}"
  echo -n "$(basename $VIRTUAL_ENV)"
  echo -n "%{$reset_color%}"
}
