font_family FiraCode Nerd Font
italic_font      auto
bold_font        auto
bold_italic_font auto

map Ctrl+c copy_or_interrupt
map Ctrl+t new_tab
map pgup previous_tab 
map pgdn next_tab

tab_bar_edge top
tab_bar_style powerline

include ./OneDark.conf
