function aliases --description="Show all custom abbreviations and functions"
    echo ""
    set_color --bold cyan
    echo "═══ Abbreviations ═══"
    set_color normal
    echo ""
    printf "  %-8s %s\n" j "Open jrnl"
    printf "  %-8s %s\n" jl "List jrnl entries (short format)"
    printf "  %-8s %s\n" jf "Open jrnl with @fire tag"
    printf "  %-8s %s\n" n "Search/create notes (→ notes)"
    printf "  %-8s %s\n" fw "Priority tasks (→ pike -w Priority)"
    printf "  %-8s %s\n" fo "Overdue tasks (→ pike -w Overdue)"
    printf "  %-8s %s\n" fu "Upcoming tasks (→ pike -w 'Next 3 Days')"
    printf "  %-8s %s\n" td "Task summary (→ pike --summary)"
    printf "  %-8s %s\n" vi "Open helix editor"
    printf "  %-8s %s\n" ls "List files with eza"
    printf "  %-8s %s\n" ll "List files (long format with git)"
    printf "  %-8s %s\n" lt "List files as tree (2 levels)"
    echo ""
    set_color --bold cyan
    echo "═══ Note Templates ═══"
    set_color normal
    echo ""
    printf "  %-12s %s\n" daily "Create/open today's daily note (daily/)"
    printf "  %-12s %s\n" weekly "Create/open weekly review (reviews/)"
    printf "  %-12s %s\n" quarterly "Create quarterly review (quarterly/)"
    printf "  %-12s %s\n" monthly "Create monthly review (monthly/)"
    printf "  %-12s %s\n" person "Create person profile (people/)"
    printf "  %-12s %s\n" project "Create project note (projects/)"
    printf "  %-12s %s\n" company "Create company research (companies/)"
    printf "  %-12s %s\n" adr "Create architecture decision record (decisions/)"
    printf "  %-12s %s\n" decision "Create decision document (decisions/)"
    printf "  %-12s %s\n" incident "Create incident report (incidents/)"
    echo ""
    set_color --bold cyan
    echo "═══ Search & Tasks ═══"
    set_color normal
    echo ""
    printf "  %-12s %s\n" notes "Search notes or create new note (alias: n)"
    printf "  %-12s %s\n" sn "Search inside notes by content (sn [-n])"
    printf "  %-12s %s\n" pike "Task dashboard (pike -h for all options)"
    printf "  %-12s %s\n" review "Create review with completed tasks (review [week|month])"
    printf "  %-12s %s\n" nw "Open notes workspace (syncs on close)"
    printf "  %-12s %s\n" notes-sync "Commit and push notes via jj"
    echo ""
    set_color --bold cyan
    echo "═══ File Search ═══"
    set_color normal
    echo ""
    printf "  %-12s %s\n" fif "Case-insensitive search in files"
    printf "  %-12s %s\n" fifs "Case-sensitive search in files"
    echo ""
    set_color --bold cyan
    echo "═══ Git & System ═══"
    set_color normal
    echo ""
    printf "  %-12s %s\n" gff "Interactive git file history explorer"
    printf "  %-12s %s\n" logg "Interactive git log explorer"
    printf "  %-12s %s\n" k "Interactive process killer"
    printf "  %-12s %s\n" mkdd "Create directory with today's date"
    printf "  %-12s %s\n" nix-cleanup "Clean up Nix store"
    printf "  %-12s %s\n" migrate-ids "Replace non-UUID note ids with UUIDs"
    echo ""
end
