gui:
  theme:
    activeBorderColor: "82aaff"    # Active border
    inactiveBorderColor: "637777" # Inactive border
    optionsTextColor: "acb4c2"    # Text color
    selectedLineBgColor: "82aaff" # Highlighted item background
    selectedRangeBgColor: "82aaff"
    panelBgColor: "011627"        # Panel background
    panelTextColor: "acb4c2"      # Panel text
    primaryTextColor: "acb4c2"    # Primary text
    secondaryTextColor: "637777"  # Comments
    errorTextColor: "ef5350"      # Errors
    warningTextColor: "ecc48d"    # Warnings
    informationTextColor: "21c7a8" # Information
    mergeConflictBgColor: "c792ea" # Merge conflicts
    mergeConflictTextColor: "011627"
    buttonColor: "82aaff"         # Button text
    progressBarColor: "21c7a8"    # Progress bar
