[[language]]
name = "bash"
file-types = [
  "sh",
  "bash",
  "zsh",
  ".bash_login",
  ".bash_logout",
  ".bash_profile",
  ".bashrc",
  ".profile",
  ".zshenv",
  "zshenv",
  ".zlogin",
  "zlogin",
  ".zlogout",
  "zlogout",
  ".zprofile",
  "zprofile",
  ".zshrc",
  "zshrc",
  ".zimrc",
  "APKBUILD",
  "PKGBUILD",
  "eclass",
  "ebuild",
  "bazelrc",
  ".bash_aliases",
  "Renviron",
  ".Renviron",
  ".xprofile",
  ".xsession",
  ".xsessionrc",
  "zsh-theme",
  "ksh",
  "cshrc",
  "tcshrc",
  ".yashrc",
  ".yash_profile",
  ".hushlogin",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  "yabairc",
  "skhdrc"
]

