source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
# antidote load ${ZDOTDIR:-$HOME}/.config/zsh/zsh_plugins.txt

# zsh-history-substring-search configuration
bindkey '^[[A' history-substring-search-up # or '\eOA'
bindkey '^[[B' history-substring-search-down # or '\eOB'
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1

ZVM_VI_INSERT_ESCAPE_BINDKEY=jj

export PATH="/home/zach/.cargo/bin:/snap/bin:$HOME/.local/bin:$PATH:/usr/local/go/bin"

eval "$(starship init zsh)" 
eval "$(zoxide init zsh)"
alias exa='exa --group-directories-first'
alias vi='nvim'
alias l='exa'
alias la='exa -la'
alias a='exa -a'
alias j='z'

