# Nightfly-inspired color palette
ZSH_HIGHLIGHT_STYLES[default]='fg=252'        # White (for unstyled text)
ZSH_HIGHLIGHT_STYLES[command]='fg=81'        # Light Blue (valid commands)
ZSH_HIGHLIGHT_STYLES[unknown-command]='fg=131' # Red (invalid commands)
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=179' # Yellow (reserved words like 'if', 'then')
ZSH_HIGHLIGHT_STYLES[builtin]='fg=110'       # Aqua (shell builtins like 'cd', 'echo')
ZSH_HIGHLIGHT_STYLES[alias]='fg=140'         # Purple (aliases)
ZSH_HIGHLIGHT_STYLES[function]='fg=81'       # Light Blue (functions)
ZSH_HIGHLIGHT_STYLES[path]='fg=110'          # Aqua (directories, paths)
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=67'    # Dark Blue (prefix for paths)
ZSH_HIGHLIGHT_STYLES[globbing]='fg=215'      # Orange (wildcards like '*')
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=131' # Red (history expansions like '!!')
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=110' # Aqua (single-hyphen options like `-a`)
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=110' # Aqua (double-hyphen options like `--help`)
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=215' # Orange (backticks)
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=252' # White (single-quoted strings)
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=252' # White (double-quoted strings)
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=140' # Purple (dollar-quoted strings)
ZSH_HIGHLIGHT_STYLES[assign]='fg=67'         # Dark Blue (variable assignments)
ZSH_HIGHLIGHT_STYLES[redirection]='fg=179'   # Yellow (input/output redirections like `>` or `<`)
