after-login-command = []
# after-startup-command = ['exec-and-forget borders']

# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = ['exec-and-forget sketchybar', 'exec-and-forget borders']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = []

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        [{ monitor."built-in" = 15 }, 50]
outer.right =      10

[mode.main.binding]

alt-period = 'layout tiles horizontal vertical'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-e = 'balance-sizes'
alt-f = 'layout floating tiling'
alt-m = 'fullscreen'
alt-r = 'reload-config'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
# same as pop_os
cmd-h = 'focus left --boundaries-action wrap-around-the-workspace'
cmd-j = 'focus down --boundaries-action wrap-around-the-workspace'
cmd-k = 'focus up --boundaries-action wrap-around-the-workspace'
cmd-l = 'focus right --boundaries-action wrap-around-the-workspace'

# setup for accordion
cmd-shift-h = [ 'join-with left','layout v_accordion' ]
cmd-shift-j = [ 'join-with down','layout h_accordion'  ]
cmd-shift-k = [ 'join-with up','layout h_accordion' ]
cmd-shift-l = [ 'join-with right','layout v_accordion']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# Move to a particular workspace
cmd-1 = 'workspace 1_Code' # terminal
cmd-2 = 'workspace 2_Mail' # Mail
cmd-3 = 'workspace 3_IM' # Slack/Messages
cmd-4 = 'workspace 4_Browser' # Browser
cmd-5 = 'workspace 5_Teams' # Teams
cmd-6 = 'workspace 6_Docs' # Docs
cmd-7 = 'workspace 7_Misc' # misc

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# Move window to a particlar workspace and follow to the workspace
cmd-shift-ctrl-1 = ['move-node-to-workspace 1_Code','workspace 1_Code']
cmd-shift-ctrl-2 = ['move-node-to-workspace 2_Mail','workspace 2_Mail']
cmd-shift-ctrl-3 = ['move-node-to-workspace 3_IM','workspace 3_IM']
cmd-shift-ctrl-4 = ['move-node-to-workspace 4_Browser','workspace 4_Browser']
cmd-shift-ctrl-5 = ['move-node-to-workspace 5_Teams','workspace 5_Teams']
cmd-shift-ctrl-6 = ['move-node-to-workspace 6_Docs','workspace 6_Docs']
cmd-shift-ctrl-7 = ['move-node-to-workspace 7_Misc','workspace 7_Misc']

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# Move window to a particlar workspace
cmd-shift-1 = ['move-node-to-workspace 1_Code']
cmd-shift-2 = ['move-node-to-workspace 2_Mail']
cmd-shift-3 = ['move-node-to-workspace 3_IM']
cmd-shift-4 = ['move-node-to-workspace 4_Browser']
cmd-shift-5 = ['move-node-to-workspace 5_Teams']
cmd-shift-6 = ['move-node-to-workspace 6_Docs']
cmd-shift-7 = ['move-node-to-workspace 7_Misc']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'
cmd-enter = 'mode adjust'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']

# Optional: Define a binding mode for window adjustments
# same as pop_os
[mode.adjust.binding]
r = ['flatten-workspace-tree', 'mode main'] # reset layout
backspace = ['close-all-windows-but-current', 'mode main']
h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'
shift-h = 'resize smart -50'
shift-l = 'resize smart +50'
shift-k = 'resize smart -50'
shift-j = 'resize smart +50'
esc = 'mode main'

# Bind windows to workspaces
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace 1_Code"

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = "move-node-to-workspace 1_Code"

[[on-window-detected]]
# if.app-id = 'com.brave.Browser.app.faolnafnngnfdaknnbpnkhgohbobgegn'
if.app-id = 'com.google.Chrome.app.faolnafnngnfdaknnbpnkhgohbobgegn'
run = "move-node-to-workspace 2_Mail"

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = "move-node-to-workspace 4_Browser"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace 4_Browser"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace 3_IM"

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = "move-node-to-workspace 3_IM"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace 5_Teams"

[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
run = "move-node-to-workspace 6_Docs"

[[on-window-detected]]
if.app-id = 'com.microsoft.rdc.macos'
run = "move-node-to-workspace 7_Misc"

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = "layout floating"

[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run= [
  "layout tiling",
]

